version: '2.1'

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  exporter-net:
    driver: bridge

volumes:
    grafana_data: {}
    vmagentdata: {}
    vmdata: {}
services:


######################################################################################
#####################           GRAFANA CONTAINER              #######################
######################################################################################



  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,michaeldmoore-multistat-panel,yesoreyeram-boomtable-panel,marcusolsson-treemap-panel,snuids-radar-panel,savantly-heatmap-panel
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION=true
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN:-example.com}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-https://example.com}
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_GOOGLE_ANALYTICS_UA_ID=${GF_ANALYTICS_GOOGLE_ANALYTICS_UA_ID:-""}
      - GF_ANALYTICS_GOOGLE_TAG_MANAGER_ID=${GF_ANALYTICS_GOOGLE_TAG_MANAGER_ID:-""}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/thegraph.json
      - GF_AUTH_DISABLE_LOGIN_FORM=${GF_AUTH_DISABLE_LOGIN_FORM:-"false"}
      - GF_AUTH_DISABLE_SIGNOUT_MENU=${GF_AUTH_DISABLE_SIGNOUT_MENU:-"false"}
      - GF_SNAPSHOTS_EXTERNAL_ENABLED=${GF_SNAPSHOTS_EXTERNAL_ENABLED:-"false"}
      - GF_SERVER_ENABLE_GZIP=true
    restart: unless-stopped
    expose:
      - 3000
    #ports:
    #  - 3000:3000
    networks:
      - exporter-net
    logging: *default-logging



######################################################################################
#####################           TheGraph Exporter              #######################
######################################################################################

  thegraph-exporter:
    image: thegraph-exporter
    container_name: thegraph-exporter
    restart: unless-stopped
    expose:
      - 8080
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - THEGRAPH_EXPORTER_NETWORK_SUBGRAPH=https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet
      - THEGRAPH_EXPORTER_ETH_NODE=${ETH_NODE:-"http://geth-mainnet:8545/"}
    networks: 
      - exporter-net
    logging: *default-logging


######################################################################################
#####################                vmagent                   #######################
######################################################################################

  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.86.2
    depends_on:
      - "victoriametrics"
      - "thegraph-exporter"
    expose:
      - 8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
      - '--remoteWrite.url=http://victoriametrics:8428/api/v1/write'
      - '-promscrape.maxScrapeSize=36777216'
    networks:
      - exporter-net
    restart: unless-stopped
    logging: *default-logging


######################################################################################
#####################            VictoriaMetrics               #######################
######################################################################################

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.86.2
    expose:
      - 8428
      - 8089
      - 2003
      - 4242
    volumes:
      - vmdata:/storage
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
      - '--influxListenAddr=:8089'
      - '--retentionPeriod=36'
      - '--selfScrapeInterval=15s'
      - '-promscrape.maxScrapeSize=36777216'
    networks:
      - exporter-net
    restart: unless-stopped
    logging: *default-logging


######################################################################################
#####################                  NGINX                   #######################
######################################################################################

  nginx:
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment: 
      - NGINX_HOST=${NGINX_HOST:-example.com}
      - NGINX_PORT=${NGINX_PORT:-80}
    ports:
      - 80:80
      #- 443:443
    networks: 
      - exporter-net
    restart: unless-stopped
    logging: *default-logging