{
 "title": "The Graph - Curators",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Delegate to us\n\nYou can support further development by delegating to **stake-machine.eth** (**[0x1692a8710dcf0dce24bd34c028479176b97ee9ef](https://network.thegraph.com/profile?id=0x1692a8710dcf0dce24bd34c028479176b97ee9ef&view=Indexing)**) \n\nAlso you can take a look at our [Indexer Dashboard](https://thegraph.stake-machine.com/d/mL29QybMk/thegraph-indexers?orgId=1&refresh=1m&var-indexer=0x1692a8710dcf0dce24bd34c028479176b97ee9ef)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Curators Name Signalled Tokens",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (curator) (thegraph_namesignal_signalled_tokens)",
     "legendFormat": "{{ curator }}"
    }
   ]
  },
  {
   "title": "Curators Name Signalled Tokens",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (curator) (thegraph_namesignal_signalled_tokens)",
     "legendFormat": "{{ curator }}"
    }
   ]
  },
  {
   "title": "Curators Name Signals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (curator) (thegraph_namesignal_amount{subgraphDeployment=~\".+\"})",
     "legendFormat": "{{ curator }}"
    }
   ]
  },
  {
   "title": "Curators Name Signals",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (curator) (thegraph_namesignal_amount{subgraphDeployment=~\".+\"})",
     "legendFormat": "{{ curator }}"
    }
   ]
  },
  {
   "title": "Curators Signal Amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (curator) (thegraph_signal_amount)",
     "legendFormat": "{{ curator }} "
    }
   ]
  },
  {
   "title": "Curators Signal Amount",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (curator) (thegraph_signal_amount)",
     "legendFormat": "{{ curator }} "
    }
   ]
  },
  {
   "title": "Tokens Signalled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thegraph_curator_tokens_signalled",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Tokens  Signalled to Subgraph Deployments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (subgraphDeployment) (thegraph_signal_signalled_tokens) - sum by (subgraphDeployment)(thegraph_signal_unsignalled_tokens)",
     "legendFormat": "{{ subgraphDeployment }}"
    }
   ]
  },
  {
   "title": "Tokens Signalled",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "thegraph_curator_tokens_signalled",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Curator Tokens  Signalled to Subgraph Deployments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (curator) (thegraph_signal_signalled_tokens) - sum by (curator)(thegraph_signal_unsignalled_tokens)",
     "legendFormat": "{{ curator }}"
    }
   ]
  },
  {
   "title": "Name Signals",
   "type": "graph",
   "description": "Total name signal summed for all bonding curves",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "thegraph_curator_namesignal_total",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Return Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "thegraph_curator_return_total", "legendFormat": "{{ id }}" }
   ]
  },
  {
   "title": "Rewards Realized",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thegraph_curator_rewards_realized",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Tokens Name Signalled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thegraph_curator_tokens_namesignalled - thegraph_curator_tokens_nameunsignalled",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Tokens Withdrawn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "thegraph_curator_tokens_withdrawn",
     "legendFormat": "{{ id }}"
    }
   ]
  }
 ]
}