{
 "title": "The Graph - Subgraph",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "subgraph_name",
    "label": "Subgraph Name",
    "query": "label_values(thegraph_subgraph_deployment_tokens_staked, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tokens Staked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_tokens_staked"
    }
   ]
  },
  {
   "title": "Total Rewards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_rewards_total{name=~\"$subgraph_name\"}"
    }
   ]
  },
  {
   "title": "Subgraph Signals",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_tokens_signalled{name=~\"$subgraph_name\"}",
     "legendFormat": "Signalled"
    },
    {
     "expr": "thegraph_subgraph_deployment_tokens_unsignalled{name=~\"$subgraph_name\"}",
     "legendFormat": "Unsignalled"
    }
   ]
  },
  {
   "title": "Signal Amount",
   "type": "stat",
   "description": "Current curation signal for this subgraph deployment",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_signal_amount"
    }
   ]
  },
  {
   "title": "Subgraph Rewards",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_rewards_delegator{name=~\"$subgraph_name\"}",
     "legendFormat": "Delegator Rewards"
    },
    {
     "expr": "thegraph_subgraph_deployment_rewards_indexer{name=~\"$subgraph_name\"}",
     "legendFormat": "Indexer Rewards"
    },
    {
     "expr": "thegraph_subgraph_deployment_query_fees_curators{name=~\"$subgraph_name\"}",
     "legendFormat": "Curators Fees"
    },
    {
     "expr": "thegraph_subgraph_deployment_query_fees_rebates{name=~\"$subgraph_name\"}",
     "legendFormat": "Query Fee Rebates"
    },
    {
     "expr": "thegraph_subgraph_deployment_query_fees{name=~\"$subgraph_name\"}",
     "legendFormat": "Query Fees"
    }
   ]
  }
 ]
}