{
 "title": "Dynamics Report",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Tokens Staked (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Epochs passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_currentepoch - thegraph_graphnetwork_currentepoch offset $__range_s"
    }
   ]
  },
  {
   "title": "Total GRT Minted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalgrtminted"
    }
   ]
  },
  {
   "title": "Tokens Staked per Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens) - (thegraph_graphnetwork_totaltokensstaked offset $__range_s + thegraph_graphnetwork_totaldelegatedtokens offset $__range_s)",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Staked growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens) - (sum(thegraph_graphnetwork_totaltokensstaked offset $__range_s + thegraph_graphnetwork_totaldelegatedtokens offset $__range_s))) / sum(thegraph_graphnetwork_totaltokensstaked offset $__range_s + thegraph_graphnetwork_totaldelegatedtokens offset $__range_s)",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Inflation APY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalsupply * 0.03 / (thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens)) ",
     "legendFormat": "APY"
    }
   ]
  },
  {
   "title": "Inflation APY Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalsupply * 0.03 / (thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens)) - thegraph_graphnetwork_totalsupply * 0.03 / (thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens) offset $__range_s",
     "legendFormat": "APY Change"
    }
   ]
  },
  {
   "title": "GRT Minted per Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalgrtminted - thegraph_graphnetwork_totalgrtminted offset $__range_s"
    }
   ]
  },
  {
   "title": "GRT Minted growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalgrtminted - thegraph_graphnetwork_totalgrtminted offset $__range_s) / thegraph_graphnetwork_totalgrtminted offset $__range_s"
    }
   ]
  },
  {
   "title": "Total GRT Supply (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalsupply",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Query fees collected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalqueryfees - thegraph_graphnetwork_totalqueryfees offset $__range_s"
    }
   ]
  },
  {
   "title": "Query fees growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalqueryfees - thegraph_graphnetwork_totalqueryfees offset $__range_s) / thegraph_graphnetwork_totalqueryfees offset $__range_s"
    }
   ]
  },
  {
   "title": "Total GRT Burned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalgrtburned"
    }
   ]
  },
  {
   "title": "Total GRT Supply change per period (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalsupply - thegraph_graphnetwork_totalsupply offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total GRT Supply growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalsupply - thegraph_graphnetwork_totalsupply offset $__range_s) / thegraph_graphnetwork_totalsupply offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "GRT Burned per period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalgrtburned - thegraph_graphnetwork_totalgrtburned offset $__range_s"
    }
   ]
  },
  {
   "title": "GRT Burned growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalgrtburned - thegraph_graphnetwork_totalgrtburned offset $__range_s) / thegraph_graphnetwork_totalgrtburned offset $__range_s"
    }
   ]
  },
  { "title": "Indexers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Indexers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_indexercount",
     "legendFormat": "Indexer Count"
    }
   ]
  },
  {
   "title": "Total Indexers Staked (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensstaked",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Indexing Indexer Rewards (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingindexerrewards",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "New Indexers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_indexercount - thegraph_graphnetwork_indexercount offset $__range_s",
     "legendFormat": "Indexer Count"
    }
   ]
  },
  {
   "title": "Indexers growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_indexercount - thegraph_graphnetwork_indexercount offset $__range_s) / thegraph_graphnetwork_indexercount offset $__range_s",
     "legendFormat": "Indexer Count"
    }
   ]
  },
  {
   "title": "Indexers Staked per Period (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensstaked - thegraph_graphnetwork_totaltokensstaked offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Indexers Staked per Period (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totaltokensstaked - thegraph_graphnetwork_totaltokensstaked offset $__range_s) / thegraph_graphnetwork_totaltokensstaked offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Indexing Indexer Rewards (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingindexerrewards - thegraph_graphnetwork_totalindexingindexerrewards offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Indexing Rewards growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalindexingindexerrewards - thegraph_graphnetwork_totalindexingindexerrewards offset $__range_s) / thegraph_graphnetwork_totalindexingindexerrewards offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  { "title": "Delegators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Delegators total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_delegatorcount"
    }
   ]
  },
  {
   "title": "Total Delegated Tokens (GRT)",
   "type": "stat",
   "description": "Total delegated tokens in the protocol",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaldelegatedtokens",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Indexing Delegators Rewards (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingdelegatorrewards",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "New Delegators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_delegatorcount - thegraph_graphnetwork_delegatorcount offset $__range_s"
    }
   ]
  },
  {
   "title": "Delegators growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_delegatorcount - thegraph_graphnetwork_delegatorcount offset $__range_s) / thegraph_graphnetwork_delegatorcount offset $__range_s"
    }
   ]
  },
  {
   "title": "Delegated per Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaldelegatedtokens - thegraph_graphnetwork_totaldelegatedtokens offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Delegated growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totaldelegatedtokens - thegraph_graphnetwork_totaldelegatedtokens offset $__range_s) / thegraph_graphnetwork_totaldelegatedtokens",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Indexing Delegators Rewards per Period (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingdelegatorrewards - thegraph_graphnetwork_totalindexingdelegatorrewards offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Indexing Delegators Rewards per Period (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalindexingdelegatorrewards - thegraph_graphnetwork_totalindexingdelegatorrewards offset $__range_s) / thegraph_graphnetwork_totalindexingdelegatorrewards offset $__range_s",
     "legendFormat": "GRT"
    }
   ]
  },
  { "title": "Curators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Curators total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_curatorcount"
    }
   ]
  },
  {
   "title": "Curators tokens signalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_signalled)"
    }
   ]
  },
  {
   "title": "Curators tokens unsignalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_unsignalled)"
    }
   ]
  },
  {
   "title": "Curator query fees total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalcuratorqueryfees"
    }
   ]
  },
  {
   "title": "New Curators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_curatorcount - thegraph_graphnetwork_curatorcount offset $__range_s"
    }
   ]
  },
  {
   "title": "Curators growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_curatorcount - thegraph_graphnetwork_curatorcount offset $__range_s) / thegraph_graphnetwork_curatorcount offset $__range_s"
    }
   ]
  },
  {
   "title": "Signalled per period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_signalled) - sum(thegraph_curator_tokens_signalled offset $__range_s)"
    }
   ]
  },
  {
   "title": "Curators growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(thegraph_curator_tokens_signalled) - sum(thegraph_curator_tokens_signalled offset $__range_s)) / sum(thegraph_curator_tokens_signalled offset $__range_s)"
    }
   ]
  },
  {
   "title": "Unsignalled per period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_unsignalled) - sum(thegraph_curator_tokens_unsignalled offset $__range_s)"
    }
   ]
  },
  {
   "title": "Curators growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(thegraph_curator_tokens_unsignalled) - sum(thegraph_curator_tokens_unsignalled offset $__range_s)) / sum(thegraph_curator_tokens_unsignalled offset $__range_s)"
    }
   ]
  },
  {
   "title": "Curator fees per period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalcuratorqueryfees - thegraph_graphnetwork_totalcuratorqueryfees offset $__range_s"
    }
   ]
  },
  {
   "title": "Curators growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totalcuratorqueryfees - thegraph_graphnetwork_totalcuratorqueryfees offset $__range_s) / thegraph_graphnetwork_totalcuratorqueryfees offset $__range_s"
    }
   ]
  },
  {
   "title": "Curators tokens namesignalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_namesignalled)"
    }
   ]
  },
  {
   "title": "Curators tokens nameunsignalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_nameunsignalled)"
    }
   ]
  },
  {
   "title": "Curator Namesignal total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_namesignal_total)"
    }
   ]
  },
  {
   "title": "Curator tokens withdrawn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_withdrawn)"
    }
   ]
  },
  {
   "title": "Namesignalled per period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_namesignalled) - sum(thegraph_curator_tokens_namesignalled offset $__range_s)"
    }
   ]
  },
  {
   "title": "Namesignalled growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(thegraph_curator_tokens_namesignalled) - sum(thegraph_curator_tokens_namesignalled offset $__range_s)) / sum(thegraph_curator_tokens_namesignalled offset $__range_s)"
    }
   ]
  },
  {
   "title": "Nameunsignalled per period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_nameunsignalled) - sum(thegraph_curator_tokens_nameunsignalled offset $__range_s)"
    }
   ]
  },
  {
   "title": "Curators nameunsignalled growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(thegraph_curator_tokens_nameunsignalled) - sum(thegraph_curator_tokens_nameunsignalled offset $__range_s)) / sum(thegraph_curator_tokens_nameunsignalled offset $__range_s)"
    }
   ]
  },
  {
   "title": "Namesignals per period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_namesignal_total) - sum(thegraph_curator_namesignal_total offset $__range_s)"
    }
   ]
  },
  {
   "title": "Namesignals growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(thegraph_curator_namesignal_total) - sum(thegraph_curator_namesignal_total offset $__range_s)) / sum(thegraph_curator_namesignal_total offset $__range_s)"
    }
   ]
  },
  {
   "title": "Curators withdrawn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_withdrawn) - sum(thegraph_curator_tokens_withdrawn offset $__range_s)"
    }
   ]
  },
  {
   "title": "Withdrawn growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(thegraph_curator_tokens_withdrawn) - sum(thegraph_curator_tokens_withdrawn offset $__range_s)) / sum(thegraph_curator_tokens_withdrawn offset $__range_s)"
    }
   ]
  },
  {
   "title": "Curators rewards realized",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_rewards_realized)"
    }
   ]
  },
  {
   "title": "Curator return total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_return_total)"
    }
   ]
  }
 ]
}