{
 "title": "TheGraph - Indexers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "indexer",
    "query": {
     "query": "label_values(thegraph_allocations_active, indexer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Delegate to us\n\nYou can support further development by delegating to **stake-machine.eth** (**[0x1692a8710dcf0dce24bd34c028479176b97ee9ef](https://network.thegraph.com/profile?id=0x1692a8710dcf0dce24bd34c028479176b97ee9ef&view=Indexing)**) \n\nAlso you can take a look at our [Indexer Dashboard](https://thegraph.stake-machine.com/d/indexers/thegraph-indexers?orgId=1&refresh=1m&var-indexer=0x1692a8710dcf0dce24bd34c028479176b97ee9ef)"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total stake (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_capacity_token{indexer=~\"$indexer\"} ",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total stake amount change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_capacity_token{indexer=~\"$indexer\"} ",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total stake (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_indexer_capacity_token{indexer=~\"$indexer\"}) * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Own Stake (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_indexer_tokens_staked{indexer=~\"$indexer\"}) ",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Own Stake (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_indexer_tokens_staked{indexer=~\"$indexer\"}) * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Delegation capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_capacity_delegated{indexer=~\"$indexer\"} / ( thegraph_indexer_tokens_staked{indexer=~\"$indexer\"} * 16) ",
     "legendFormat": "delegated"
    }
   ]
  },
  {
   "title": "Overdelegation Dilution",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_overdelegationdilution{indexer=~\"$indexer\"}"
    }
   ]
  },
  {
   "title": "Token utilzation",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_tokens_allocated{indexer=~\"$indexer\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "thegraph_indexer_capacity_token{indexer=~\"$indexer\"} - thegraph_indexer_tokens_allocated{indexer=~\"$indexer\"}",
     "legendFormat": "Unallocated"
    }
   ]
  },
  {
   "title": "Tokens Controlled",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_tokens_staked{indexer=~\"$indexer\"} ",
     "legendFormat": "Staked"
    },
    {
     "expr": "thegraph_indexer_tokens_delegated{indexer=~\"$indexer\"} ",
     "legendFormat": "Delegated"
    },
    {
     "expr": "thegraph_indexer_tokens_unstaked{indexer=~\"$indexer\"} ",
     "legendFormat": "Unstaked"
    }
   ]
  },
  { "title": "Rewards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Query fees collected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_fees_query_collected{indexer=~\"$indexer\"}",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Potential rewards (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_allocations_active{indexer=~\"$indexer\", ipfs_hash=~\".+\"}  * on (indexer) group_left(indexer) (thegraph_indexer_fees_rewards_cut{indexer=~\"$indexer\"} / 1000000))",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Potential rewards (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_allocations_active{indexer=~\"$indexer\"}  * on (indexer) group_left(indexer) (thegraph_indexer_fees_rewards_cut{indexer=~\"$indexer\"} / 1000000)) * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Indexing Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(thegraph_graphnetwork_totalsupply) * 0.03 / (sum(thegraph_graphnetwork_totaltokensstaked) + sum(thegraph_graphnetwork_totaldelegatedtokens))) - (sum(thegraph_graphnetwork_totalsupply) * 0.03 / (sum(thegraph_graphnetwork_totaltokensstaked) + sum(thegraph_graphnetwork_totaldelegatedtokens))) * ((thegraph_indexer_fees_rewards_cut{indexer=~\"$indexer\"} / 1000000) - thegraph_indexer_ownstakeratio{indexer=~\"$indexer\"})) * (1- thegraph_indexer_overdelegationdilution{indexer=\"$indexer\"})",
     "legendFormat": "Delegators Indexing Rewards APY"
    },
    {
     "expr": "thegraph_indexer_indexing_rewards_effective_cut{indexer=~\"$indexer\"}",
     "legendFormat": "Indexer Effective Cut"
    }
   ]
  },
  {
   "title": "Potential Rewards Rate per Hour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "GRT" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "3600 * sum by (indexer)(rate(thegraph_allocations_active{indexer=~\"$indexer\",ipfs_hash=~\".+\"}[1h]))",
     "legendFormat": "{{allocation}}"
    }
   ]
  },
  {
   "title": "Potential Rewards Rate per Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "GRT" } },
   "targets": [
    {
     "expr": "3600 * (rate(thegraph_allocations_active{indexer=~\"$indexer\",ipfs_hash=~\".+\"}[1h]))",
     "legendFormat": "{{allocation}}"
    }
   ]
  },
  {
   "title": "Total Rewards",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_fees_query_collected{indexer=~\"$indexer\"} ",
     "legendFormat": "Query Fees"
    },
    {
     "expr": "thegraph_indexer_rewards_delegator_indexing{indexer=~\"$indexer\"} ",
     "legendFormat": "Delegator Rewards"
    },
    {
     "expr": "thegraph_indexer_rewards_indexing{indexer=~\"$indexer\"} ",
     "legendFormat": "Indexer Rewards"
    },
    {
     "expr": "thegraph_indexer_fees_query_delegator{indexer=~\"$indexer\"} ",
     "legendFormat": "Delegator Query Fees"
    }
   ]
  },
  {
   "title": "Indexing Reward Cut",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_fees_rewards_cut{indexer=~\"$indexer\"} / 10000 ",
     "legendFormat": "Indexer gets"
    },
    {
     "expr": "100 - thegraph_indexer_fees_rewards_cut{indexer=~\"$indexer\"} / 10000 ",
     "legendFormat": "Delegator gets"
    }
   ]
  },
  {
   "title": "Query Fee Cut",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_fees_query_cut{indexer=~\"$indexer\"} / 10000",
     "legendFormat": "Indexer gets"
    },
    {
     "expr": "100 - thegraph_indexer_fees_query_cut{indexer=~\"$indexer\"} / 10000",
     "legendFormat": "Delegators gets"
    }
   ]
  },
  {
   "title": "Total Rewards History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_indexer_fees_query_collected{indexer=~\"$indexer\"} ",
     "legendFormat": "Query Fees"
    },
    {
     "expr": "thegraph_indexer_rewards_delegator_indexing{indexer=~\"$indexer\"} ",
     "legendFormat": "Delegator Rewards"
    },
    {
     "expr": "thegraph_indexer_rewards_indexing{indexer=~\"$indexer\"} ",
     "legendFormat": "Indexer Rewards"
    },
    {
     "expr": "thegraph_indexer_fees_query_delegator{indexer=~\"$indexer\"} ",
     "legendFormat": "Delegator Query Fees"
    }
   ]
  },
  {
   "title": "Indexing Reward Cut History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_indexer_fees_rewards_cut{indexer=~\"$indexer\"} / 10000 ",
     "legendFormat": "Indexer gets"
    },
    {
     "expr": "100 - thegraph_indexer_fees_rewards_cut{indexer=~\"$indexer\"} / 10000 ",
     "legendFormat": "Delegator gets"
    }
   ]
  },
  {
   "title": "Query Fee Cut History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_indexer_fees_query_cut{indexer=~\"$indexer\"} / 10000",
     "legendFormat": "Indexer gets"
    },
    {
     "expr": "100 - thegraph_indexer_fees_query_cut{indexer=~\"$indexer\"} / 10000",
     "legendFormat": "Delegators gets"
    }
   ]
  },
  { "title": "Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Active Allocations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_allocations_active_count{indexer=~\"$indexer\"} ",
     "legendFormat": "Active Allocation Number"
    }
   ]
  },
  {
   "title": "Allocation Reward (Contract)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_allocations_active{indexer=~\"$indexer\",ipfs_hash=~\".+\"} ",
     "legendFormat": "{{allocation}}"
    }
   ]
  },
  {
   "title": "Forced Allocation Closures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_indexer_forced_closures{indexer=~\"$indexer\"} ",
     "legendFormat": "Forced Closures"
    }
   ]
  },
  { "title": "Delegators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Number of Delegators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(thegraph_delegatedstake_tokens_staked{indexer=~\"$indexer\"})"
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_tokens_staked{indexer=~\"$indexer\"}",
     "legendFormat": "{{delegator}}"
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_tokens_staked{indexer=~\"$indexer\"}",
     "legendFormat": "{{delegator}}"
    }
   ]
  },
  {
   "title": "Delegators Unrealized Yield",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_rewards_unrealized{indexer=~\"$indexer\"} / thegraph_delegatedstake_tokens_staked{indexer=~\"$indexer\"}",
     "legendFormat": "{{delegator}}"
    }
   ]
  }
 ]
}