{
 "title": "The Graph - Curator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "curator_id",
    "label": "Curator ID",
    "query": {
     "query": "label_values(thegraph_curator_return_total, id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Delegate to us\n\nYou can support further development by delegating to **stake-machine.eth** (**[0x1692a8710dcf0dce24bd34c028479176b97ee9ef](https://network.thegraph.com/profile?id=0x1692a8710dcf0dce24bd34c028479176b97ee9ef&view=Indexing)**) \n\nAlso you can take a look at our [Indexer Dashboard](https://thegraph.stake-machine.com/d/indexers/thegraph-indexers?orgId=1&refresh=1m&var-indexer=0x1692a8710dcf0dce24bd34c028479176b97ee9ef)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Name Signals",
   "type": "stat",
   "description": "Total name signal summed for all bonding curves",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_curator_namesignal_total{id=~\"$curator_id\"}",
     "legendFormat": "Name Signals"
    }
   ]
  },
  {
   "title": "Return Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_curator_return_total{id=~\"$curator_id\"}",
     "legendFormat": "Return Total"
    }
   ]
  },
  {
   "title": "Rewards Realized",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_curator_rewards_realized{id=~\"$curator_id\"}",
     "legendFormat": "Rewards Realized"
    }
   ]
  },
  {
   "title": "Tokens Withdrawn",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_curator_tokens_withdrawn{id=~\"$curator_id\"}",
     "legendFormat": "Tokens Withdrawn"
    }
   ]
  },
  {
   "title": "Tokens Signalled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_curator_tokens_signalled{id=~\"$curator_id\"}",
     "legendFormat": "Signalled"
    },
    {
     "expr": "thegraph_curator_tokens_unsignalled{id=~\"$curator_id\"}",
     "legendFormat": "Unsignalled"
    }
   ]
  },
  {
   "title": "Tokens Name Signalled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_curator_tokens_namesignalled{id=~\"$curator_id\"}",
     "legendFormat": "Name Signalled"
    },
    {
     "expr": "thegraph_curator_tokens_nameunsignalled{id=~\"$curator_id\"}",
     "legendFormat": "Name Unsignalled"
    }
   ]
  }
 ]
}