{
 "title": "TheGraph - Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Delegate to us\n\nYou can support further development by delegating to **stake-machine.eth** (**[0x1692a8710dcf0dce24bd34c028479176b97ee9ef](https://thegraph.com/explorer/profile/0x1692a8710dcf0dce24bd34c028479176b97ee9ef?view=Indexing&chain=mainnet)**) \n\nAlso you can take a look at our [Indexer Dashboard](https://thegraph.stake-machine.com/d/indexers/thegraph-indexers?orgId=1&refresh=1m&var-indexer=0x1692a8710dcf0dce24bd34c028479176b97ee9ef)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Indexers Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "expr": "thegraph_indexers_info{geohash=~\".+\"}"
    }
   ]
  },
  {
   "title": "Total Network Rewards",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingdelegatorrewards",
     "legendFormat": "Total Indexing Delegator Rewards"
    },
    {
     "expr": "thegraph_graphnetwork_totalindexingindexerrewards",
     "legendFormat": "Total Indexing Indexer Rewards"
    },
    {
     "expr": "thegraph_graphnetwork_totalqueryfees",
     "legendFormat": "Total Query Fees"
    },
    {
     "expr": "thegraph_graphnetwork_totalcuratorqueryfees",
     "legendFormat": "Total Curator Query Fees"
    }
   ]
  },
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Tokens Staked (GRT)",
   "type": "stat",
   "description": "The total amount of GRT staked in the staking contract",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Indexing Rewards (GRT)",
   "type": "stat",
   "description": "Total indexing rewards earned. Including delegators and indexers parts",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingrewards",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Unallocated Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_allocations_active)"
    }
   ]
  },
  {
   "title": "Total GRT Supply (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalsupply",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total GRT Supply (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalsupply * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Total Tokens Staked Amount Changed",
   "type": "stat",
   "description": "The total amount of GRT staked in the staking contract",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Staked % Changed",
   "type": "stat",
   "description": "The total amount of GRT staked in the staking contract",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens) - (sum(thegraph_graphnetwork_totaltokensstaked offset $__range_s + thegraph_graphnetwork_totaldelegatedtokens offset $__range_s))) / sum(thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens)",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Tokens Staked (USD)",
   "type": "stat",
   "description": "The total amount of GRT staked in the staking contract",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens) * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Total Indexing Rewards (USD)",
   "type": "stat",
   "description": "Total indexing rewards earned. Including delegators and indexers parts",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingrewards * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Total GRT Minted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalgrtminted"
    }
   ]
  },
  {
   "title": "Total GRT Burned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalgrtburned"
    }
   ]
  },
  {
   "title": "Tokens Staked in Subgraphs",
   "type": "stat",
   "description": "Total stake of all indexers on all Subgraph deployments",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_subgraph_deployment_tokens_staked)",
     "legendFormat": "Token Staked"
    }
   ]
  },
  {
   "title": "Total Unstaked Tokens Locked",
   "type": "stat",
   "description": "Total tokens that are currently locked or withdrawable in the network from unstaking",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalunstakedtokenslocked"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_currentepoch"
    }
   ]
  },
  {
   "title": "Total Taxed Query Fees",
   "type": "stat",
   "description": "Total query fees taxed by the protocol",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltaxedqueryfees"
    }
   ]
  },
  {
   "title": "Total Unclaimed Query Fees Rebate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalunclaimedqueryfeerebates"
    }
   ]
  },
  {
   "title": "GRT/USD",
   "type": "stat",
   "description": "Price from Coingecko",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "thegraph_grt_usd" }
   ]
  },
  {
   "title": "Total Tokens Allocated",
   "type": "stat",
   "description": "Total GRT currently in allocation",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensallocated"
    }
   ]
  },
  {
   "title": "Total Active Allocations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "thegraph_allocations_active_count",
     "legendFormat": "Number of active allocations"
    }
   ]
  },
  {
   "title": "Total Subgraphs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_subgraphcount"
    }
   ]
  },
  {
   "title": "Inflation APY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalsupply * 0.03 / (thegraph_graphnetwork_totaltokensstaked + thegraph_graphnetwork_totaldelegatedtokens)",
     "legendFormat": "APY"
    }
   ]
  },
  {
   "title": "Total Tokens Claimable",
   "type": "stat",
   "description": "Total tokens that are settled and waiting to be claimed",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensclaimable"
    }
   ]
  },
  {
   "title": "GRT/USD Change",
   "type": "stat",
   "description": "Price from Coingecko",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(thegraph_grt_usd - thegraph_grt_usd offset $__range_s) / thegraph_grt_usd"
    }
   ]
  },
  { "title": "Delegators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Delegators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_delegatorcount",
     "legendFormat": "Total"
    },
    {
     "expr": "count(thegraph_delegator_tokens_staked)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Total Delegator Query Fee Rebates",
   "type": "stat",
   "description": "Total query fees rebates claimed by delegators",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaldelegatorqueryfeerebates"
    }
   ]
  },
  {
   "title": "Total Indexing Delegators Rewards (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingdelegatorrewards",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Indexing Delegators Rewards (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingdelegatorrewards * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Total Delegated Tokens (GRT)",
   "type": "stat",
   "description": "Total delegated tokens in the protocol",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaldelegatedtokens",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Delegated Tokens (USD)",
   "type": "stat",
   "description": "Total delegated tokens in the protocol",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaldelegatedtokens * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Total Delegators",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (delegator)(thegraph_delegatedstake_tokens_staked)",
     "legendFormat": "{{delegator}}"
    }
   ]
  },
  {
   "title": "Unrealized Delegators Yield",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (delegator)(thegraph_delegatedstake_rewards_unrealized) / sum by (delegator)(thegraph_delegatedstake_tokens_staked)",
     "legendFormat": "{{delegator}}"
    }
   ]
  },
  { "title": "Indexers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Total Indexers Staked (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensstaked",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Indexers Staked (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensstaked * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Total Indexing Indexer Rewards (GRT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingindexerrewards",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Total Indexing Indexer Rewards (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexingindexerrewards * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Indexers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_indexercount",
     "legendFormat": "Total"
    },
    {
     "expr": "count(group by (indexer) (thegraph_indexer_tokens_staked))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Total Active Indexers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (indexer) (thegraph_allocations_active))"
    }
   ]
  },
  {
   "title": "Indexer Staked Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_stakedindexerscount"
    }
   ]
  },
  {
   "title": "Total Indexer Query Fee Rebates",
   "type": "stat",
   "description": "Total query fees rebates claimed by indexers",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexerqueryfeerebates"
    }
   ]
  },
  {
   "title": "Total Indexer Query Fees Collected",
   "type": "stat",
   "description": "Total query fees collected by indexers",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalindexerqueryfeescollected"
    }
   ]
  },
  {
   "title": "Total tokens Indexers control",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "thegraph_indexer_capacity_token",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Total Indexers Collected Rewards",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "thegraph_indexer_rewards_earned",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  { "title": "Curators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Total Curators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_curatorcount"
    }
   ]
  },
  {
   "title": "Total Curator Query Fees",
   "type": "stat",
   "description": "Total query fees payed to curators",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalcuratorqueryfees"
    }
   ]
  },
  {
   "title": "Total Tokens Signalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaltokensignalled"
    }
   ]
  },
  {
   "title": "Total Tokens Unsignalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_unsignalled)"
    }
   ]
  },
  {
   "title": "Total Tokens Signalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_signalled)"
    }
   ]
  },
  {
   "title": "Total Name Signals",
   "type": "stat",
   "description": "Total name signal summed for all bonding curves",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_namesignal_total)"
    }
   ]
  },
  {
   "title": "Total Tokens Name Signalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_namesignalled)"
    }
   ]
  },
  {
   "title": "Total Tokens Name Unsignalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_curator_tokens_nameunsignalled)"
    }
   ]
  },
  {
   "title": "Indexer Rewards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uncollected Rewards by Indexers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "GRT" } },
     "yaxes": [
      { "format": "GRT" }
     ],
     "targets": [
      {
       "expr": "sum(thegraph_allocations_active) by (indexer)",
       "legendFormat": "{{indexer}}"
      }
     ]
    },
    {
     "title": "Indexers Reward Rate per Hour",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "GRT" } },
     "yaxes": [
      { "format": "GRT" }
     ],
     "targets": [
      {
       "expr": "3600 * sum by (indexer)(rate(thegraph_allocations_active[1h]))",
       "legendFormat": "{{indexer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uncollected Rewards per Active Allocation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "GRT" } },
     "yaxes": [
      { "format": "GRT" }
     ],
     "targets": [
      { "expr": "thegraph_allocations_active", "legendFormat": "{{allocation}}" }
     ]
    }
   ]
  }
 ]
}