{
 "title": "TheGraph - Delegator",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "delegator",
    "query": {
     "query": "label_values(thegraph_delegatedstake_tokens_staked, delegator)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Delegate to us\n\nYou can support further development by delegating to **stake-machine.eth** (**[0x1692a8710dcf0dce24bd34c028479176b97ee9ef](https://network.thegraph.com/profile?id=0x1692a8710dcf0dce24bd34c028479176b97ee9ef&view=Indexing)**) \n\nAlso you can take a look at our [Indexer Dashboard](https://thegraph.stake-machine.com/d/indexers/thegraph-indexers?orgId=1&refresh=1m&var-indexer=0x1692a8710dcf0dce24bd34c028479176b97ee9ef)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Delegated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"} + thegraph_delegatedstake_rewards_realized{delegator=~\"$delegator\"} + thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"}-thegraph_delegatedstake_tokens_unstaked{delegator=~\"$delegator\"})",
     "legendFormat": "GRT"
    },
    {
     "expr": "sum(thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"} + thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} + thegraph_delegatedstake_rewards_realized{delegator=~\"$delegator\"} -thegraph_delegatedstake_tokens_unstaked{delegator=~\"$delegator\"}) * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Unrealized Profit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"}) / sum(thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"})",
     "legendFormat": "GRT"
    }
   ]
  },
  {
   "title": "Potential Rewards Rate per Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "GRT" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "3600 * sum(rate(thegraph_allocations_active[1h]) * on (indexer) group_left(indexer) (thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} * 0 + 1) * on (indexer) group_left(indexer) (1 - thegraph_indexer_fees_rewards_cut / 1000000) * on (indexer) group_left(indexer) thegraph_delegatedstake_indexer_delegator_percent{delegator=~\"$delegator\"})",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Potential rewards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_allocations_active * on (indexer) group_left(indexer) (thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} * 0 + 1) * on (indexer) group_left(indexer) (1 - thegraph_indexer_fees_rewards_cut / 1000000) * on (indexer) group_left(indexer) thegraph_delegatedstake_indexer_delegator_percent{delegator=~\"$delegator\"})",
     "legendFormat": "GRT"
    },
    {
     "expr": "sum(thegraph_allocations_active * on (indexer) group_left(indexer) (thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} * 0 + 1) * on (indexer) group_left(indexer) (1 - thegraph_indexer_fees_rewards_cut / 1000000) * on (indexer) group_left(indexer) thegraph_delegatedstake_indexer_delegator_percent{delegator=~\"$delegator\"}) * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Total Rewards",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_delegator_rewards_realized{delegator=~\"$delegator\"}",
     "legendFormat": "Realized Rewards"
    },
    {
     "expr": "sum(thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"})",
     "legendFormat": "Unrealized Rewards"
    }
   ]
  },
  {
   "title": "Total Rewards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_delegator_rewards_realized{delegator=~\"$delegator\"}",
     "legendFormat": "Realized Rewards"
    },
    {
     "expr": "sum(thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"})",
     "legendFormat": "Unrealized Rewards"
    }
   ]
  },
  {
   "title": "Active Indexers Allocations",
   "type": "piechart",
   "description": "Format: Indexer - Allocation",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_allocations_active * on (indexer) group_left(indexer) (thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} * 0 + 1)",
     "legendFormat": "{{indexer}} -  {{allocation}}"
    }
   ]
  },
  {
   "title": "Indexers Allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_allocations_active * on (indexer) group_left(indexer) (thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} * 0 + 1)",
     "legendFormat": "{{indexer}} - {{allocation}}"
    }
   ]
  },
  {
   "title": "Indexer Delegation Pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_indexer_delegator_percent{delegator=~\"$delegator\"}",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Potential rewards (GRT)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (indexer) (thegraph_allocations_active * on (indexer) group_left(indexer) ((thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} - thegraph_delegatedstake_tokens_unstaked{delegator=~\"$delegator\"}) * 0 + 1) * on (indexer) group_left(indexer) (1 - thegraph_indexer_fees_rewards_cut / 1000000) * on (indexer) group_left(indexer) thegraph_delegatedstake_indexer_delegator_percent{delegator=~\"$delegator\"})",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Unrealized Yield by Indexers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"} / sum(thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} - thegraph_delegatedstake_tokens_unstaked{delegator=~\"$delegator\"})",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Unrealized Rewards by Indexers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"}",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Unrealized Rewards by Indexers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"}",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Delegated to Indexers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} - thegraph_delegatedstake_tokens_unstaked{delegator=~\"$delegator\"} + thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"} + thegraph_delegatedstake_rewards_realized{delegator=~\"$delegator\"}",
     "legendFormat": "{{indexer}}"
    }
   ]
  },
  {
   "title": "Delegated to Indexers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thegraph_delegatedstake_tokens_staked{delegator=~\"$delegator\"} - thegraph_delegatedstake_tokens_unstaked{delegator=~\"$delegator\"} + thegraph_delegatedstake_rewards_unrealized{delegator=~\"$delegator\"} + thegraph_delegatedstake_rewards_realized{delegator=~\"$delegator\"}",
     "legendFormat": "{{indexer}}"
    }
   ]
  }
 ]
}