{
 "title": "The Graph - Vested Tokens",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total Unused Vested Tokens (GRT)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(thegraph_vested_tokens)", "legendFormat": "GRT" }
   ]
  },
  {
   "title": "Amount Change (GRT)",
   "type": "stat",
   "description": "Total Unused Vested Tokens Amount Change (GRT)",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(thegraph_vested_tokens)", "legendFormat": "GRT" }
   ]
  },
  {
   "title": "Total Unused Vested Tokens (USD)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_vested_tokens) * thegraph_grt_usd",
     "legendFormat": "USD"
    }
   ]
  },
  {
   "title": "Wallets number",
   "type": "stat",
   "description": "Number of non-empty wallets",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(thegraph_vested_tokens)", "legendFormat": "GRT" }
   ]
  },
  {
   "title": "Unused Vested Tokens",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "thegraph_vested_tokens", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Unused Vested Tokens",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "thegraph_vested_tokens", "legendFormat": "{{address}}" }
   ]
  }
 ]
}