{
 "title": "The Graph - L2 Transfer",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Tokens Transferred to L2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(thegraph_graphnetwork_totalsignalledtokenstransferredtol2{job=\"thegraph-exporter\"},thegraph_graphnetwork_totaldelegatedtokenstransferredtol2{job=\"thegraph-exporter\"},thegraph_graphnetwork_totalstakedtokenstransferredtol2{job=\"thegraph-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Staked Tokens Transferred to L2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalstakedtokenstransferredtol2{job=\"thegraph-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delegated Tokens Transferred to L2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totaldelegatedtokenstransferredtol2{job=\"thegraph-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Signalled Tokens Transferred to L2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalsignalledtokenstransferredtol2{job=\"thegraph-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Tokens Transferred",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "thegraph_graphnetwork_totalstakedtokenstransferredtol2{job=\"thegraph-exporter\"}",
     "legendFormat": "Total Staked Tokens Transferred to L2"
    },
    {
     "expr": "thegraph_graphnetwork_totaldelegatedtokenstransferredtol2{job=\"thegraph-exporter\"}",
     "legendFormat": "Total Delegated Tokens Transferred to L2"
    },
    {
     "expr": "thegraph_graphnetwork_totalsignalledtokenstransferredtol2{job=\"thegraph-exporter\"}",
     "legendFormat": "Total Signalled Tokens Transferred to L2"
    }
   ]
  },
  {
   "title": "Indexers Staked Tokens Transferred to L2",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "thegraph_indexer_stakedtokenstransferredtol2{job=\"thegraph-exporter\"} != 0",
     "legendFormat": "{{indexer}}"
    }
   ]
  }
 ]
}