{
 "title": "The Graph - Subgraphs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Subgraphs Stake",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_tokens_staked",
     "legendFormat": "{{ipfs_hash}}"
    }
   ]
  },
  {
   "title": "Subgraphs Stake (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_tokens_staked",
     "legendFormat": "{{ipfs_hash}}"
    }
   ]
  },
  {
   "title": "Subgraphs Stake (%)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_tokens_staked",
     "legendFormat": "{{ipfs_hash}}"
    }
   ]
  },
  {
   "title": "Subgraphs Signaled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_tokens_signalled",
     "legendFormat": "{{ipfs_hash}} ({{name}})"
    }
   ]
  },
  {
   "title": "Subgraphs Unsignaled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_tokens_unsignalled",
     "legendFormat": "{{ipfs_hash}}"
    }
   ]
  },
  {
   "title": "Subgraphs Fees",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_query_fees",
     "legendFormat": "{{ipfs_hash}}"
    }
   ]
  },
  {
   "title": "Subgraphs Fees",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "thegraph_subgraph_deployment_query_fees",
     "legendFormat": "{{ipfs_hash}}"
    }
   ]
  }
 ]
}